@startuml c4-context

!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

LAYOUT_WITH_LEGEND()
LAYOUT_TOP_DOWN()

Person_Ext(Visitor, "Посетитель Сайта", "Посетитель сайта, оформляющий заявку на депозит")
Person(Manager, "Менеджер call-центра", "Менеджер call-центра, обрабатывающий заявку на депозит")   
Person(Back, "Сотрудник бэк-офиса", "Сотрудник бэк-офиса, подтверждающий заявку на депозит")

System_Boundary(std, "Банк Стандарт", "Информационные системы банка Стандарт") {
    System(site, "Сайт")    
    System(ib, "Интернет-банк") 
    System(call, "Система call-центра") 
    System(abs, "Автоматизированная банковская система (АБС)")    
    System(kafka, "Система очередей Kafka") 
    System(sms, "СМС-шлюз телеком-оператора")      

}

System_Ext(telco, "Телеком-оператор")  

Rel_D(Visitor, site, "Оформляет заявку на депозит", "HTTPS")
Rel(site, ib, "Отправляет заявку на депозит", "HTTPS")
Rel(ib, kafka, "Отправляет сообщение об оформлении заявки на депозит", "Kafka")
Rel(call, kafka, "Получает сообщение об оформлении заявки на депозит", "Kafka")

Rel(Manager, call, "Получает список заявок на депозит", "HTTPS")
Rel(Manager, call, "Указывает процент ставки в заявке", "HTTPS")
Rel(call, kafka, "Отправляет сообщение об изменении процента ставки", "Kafka")
Rel(ib, kafka, "Получает сообщение об изменении процента ставки", "Kafka")
Rel(abs, kafka, "Получает сообщение об изменении процента ставки", "Kafka")

Rel(Back, abs, "Получает список неподтвержденных заявок на депозит", "HTTPS")
Rel(Back, abs, "Подтверждает заявку на депозит", "HTTPS")
Rel(abs, kafka, "Отправляет сообщение об изменении статуса заявки", "Kafka")
Rel(ib, kafka, "Получает сообщение об изменении статуса заявки", "Kafka")
Rel(call, kafka, "Получает сообщение об изменении статуса заявки", "Kafka")
Rel_R(abs, sms, "Отправляет запрос на SMS-уведомление о подтверждении заявки", "HTTPS")
Rel_R(sms, telco, "Отправляет запрос на SMS-уведомление о подтверждении заявки", "SMPP")

Rel_U(telco, Visitor, "Отправляет SMS-уведомление о подтверждении заявки", "SMS")

@enduml