@startuml UC2

title Обработать заявку на депозит

hide footbox
autonumber 1

actor "Менеджер call-центра" as manager

participant "Интернет-банк\nback-end" as ib
participant "Система call-центра" as call
participant "Автоматизированная банковская система\n(АБС)" as abs
participant "Система очередей\nKafka" as kafka

call ->> kafka : Получить сообщение\nоб оформлении заявки\nна депозит

manager -> call : Получить список заявок на депозит
call --> manager : Отправить список заявок на депозит
manager -> call : Указать процент ставки в заявке`
call --> manager : Подтверждение о приеме процента ставки
call -> call : Сохранить процент ставки в заявке
call ->> kafka : Отправить сообщение\nоб изменении\nпроцента ставки
ib ->> kafka : Получить сообщение\nоб изменении\nпроцента ставки 
ib -> ib : Обновить информацию в заявке на депозит 
abs ->> kafka : Получить сообщение\nоб изменении\nпроцента ставки
note left: Триггер для старта UC3

@enduml