@startuml UC3 

title Подтвердить заявку на депозит

hide footbox
autonumber 1

actor "Посетитель Сайта" as visitor
actor "Менеджер бэк-офиса" as back

participant "Интернет-банк\nback-end" as ib
participant "Система call-центра" as call
participant "Автоматизированная банковская система\n(АБС)" as abs
participant "Система очередей\nKafka" as kafka
participant "Система отправки\nSMS-уведомлений" as sms

abs ->> kafka : Получить сообщение\nоб изменении\nпроцента ставки
abs -> abs : Создать неподтвержденную заявку\nна депозит
back -> abs : Получить список неподтвержденных заявок на депозит
abs --> back : Отправить список неподтвержденных заявок на депозит
back -> abs : Подтвердить заявку на депозит 
abs --> back : Отправить подтверждение о приеме заявки на депозит
abs -> abs : Изменить статус заявки на депозит на "подтверждена"
abs ->> kafka : Отправить сообщение\nоб изменении\nстатуса заявки
ib ->> kafka : Получить сообщение\nоб изменении\nстатуса заявки
ib -> ib : Обновить информацию в заявке на депозит
call ->> kafka : Получить сообщение\nоб изменении\nстатуса заявки
call -> call : Обновить информацию в заявке на депозит
abs ->> sms : Отправить запрос\nна SMS-уведомление\nо подтверждении заявки
sms ->> visitor : SMS-уведомление\nо подтверждении заявки

@enduml